export const Types = {
  SET_PIZZAS: "SET_PIZZAS",
  SET_LOADED: "SET_LOADED",
  SET_SORT_BY: "SET_SORT_BY",
  SET_CATEGORY: "SET_CATEGORY",
  ADD_PIZZA_TO_CART: "ADD_PIZZA_TO_CART",
  CLEAR_CART: "CLEAR_CART",
  INCREMENT_PIZZA: "INCREMENT_PIZZA",
  DECREMENT_PIZZA: "DECREMENT_PIZZA",
  DELETE_PIZZA: "DELETE_PIZZA",
};
